arch:
- amd64
- aarch64
backup_exclude:
- '*/server/**'
- '*/scrypted_nvr/**'
- '*/scrypted_data/plugins/**'
description: Scrypted - High performance home video integration and automation platform
host_network: true
image: koush/scrypted
init: false
map:
- path: /data/scrypted_data
  read_only: false
  type: addon_config
name: Scrypted
ports:
  10443/tcp: 10443
ports_description:
  10443/tcp: Scrypted UI
slug: scrypted
url: https://github.com/koush/scrypted
version: v0.122.0-jammy-full
webui: http://[HOST]:[PORT:10443]
