name: Scrypted-armv7
version: latest
slug: scrypted-armv7
description: Scrypted is a high performance home video integration and automation
  platform
url: https://hub.docker.com/r/blackwell97001/scrypted-armv7/tags
image: blackwell97001/scrypted-armv7
arch:
- armv7
init: false
ingress: true
ingress_port: 11080
panel_icon: mdi:memory
hassio_api: true
homeassistant_api: true
ingress_stream: true
host_network: true
gpio: true
usb: true
uart: true
video: true
environment:
  SCRYPTED_INSTALL_PLUGIN: '@scrypted/homeassistant'
  SCRYPTED_VOLUME: /data/scrypted_data
  SCRYPTED_NVR_VOLUME: /data/scrypted_nvr
  SCRYPTED_ADMIN_ADDRESS: 172.30.32.2
  SCRYPTED_ADMIN_USERNAME: homeassistant
  SCRYPTED_INSTALL_ENVIRONMENT: ha
backup_exclude:
- '*/server/**'
- '*/scrypted_nvr/**'
- '*/scrypted_data/plugins/**'
map:
- homeassistant_config:rw
- media:rw
- share:rw
devices:
- /dev/mem
- /dev/dri/renderD128
- /dev/apex_0
- /dev/apex_1
- /dev/apex_2
- /dev/apex_3
- /dev/dri/card0
- /dev/vchiq
- /dev/video10
- /dev/video0
